// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaidBot.Data;

#nullable disable

namespace RaidBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RaidBot.Data.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expansions");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "The Burning Crusade",
                            ShortName = "TBC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wrath of the Lich King",
                            ShortName = "WotLK"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cataclysm",
                            ShortName = "Cata"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mists of Pandaria",
                            ShortName = "Mists"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Warlords of Draenor",
                            ShortName = "WoD"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Legion",
                            ShortName = "Legion"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Battle for Azeroth",
                            ShortName = "BfA"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shadowlands",
                            ShortName = "SL"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dragonflight",
                            ShortName = "DF"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Classic (Alliance)",
                            ShortName = "Classic"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Classic (Horde)",
                            ShortName = "Classic"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Season of Discovery (Alliance)",
                            ShortName = "SoD"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Season of Discovery (Horde)",
                            ShortName = "SoD"
                        });
                });

            modelBuilder.Entity("RaidBot.Data.ExpansionClass", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassId", "ExpansionId");

                    b.HasIndex("ExpansionId");

                    b.ToTable("ExpansionClasses");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 2
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 3
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 4
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 11,
                            ExpansionId = 5
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 11,
                            ExpansionId = 6
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 11,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 12,
                            ExpansionId = 7
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 11,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 12,
                            ExpansionId = 8
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 11,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 12,
                            ExpansionId = 9
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 10,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 11,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 12,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 13,
                            ExpansionId = 10
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 101
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 102
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 4,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 111
                        },
                        new
                        {
                            ClassId = 1,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 2,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 3,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 5,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 6,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 7,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 8,
                            ExpansionId = 112
                        },
                        new
                        {
                            ClassId = 9,
                            ExpansionId = 112
                        });
                });

            modelBuilder.Entity("RaidBot.Data.GuildExpansionConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CreateRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.ToTable("GuildExpansionConfigurations");
                });

            modelBuilder.Entity("RaidBot.Data.PlayerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "<:druid:945492995321528370>",
                            Name = "Druid",
                            SearchTerms = "druid"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "<:hunter:945492995417972736>",
                            Name = "Hunter",
                            SearchTerms = "hunter;huntard"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "<:mage:945492995225030697>",
                            Name = "Mage",
                            SearchTerms = "mage"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "<:paladin:945492995321495582>",
                            Name = "Paladin",
                            SearchTerms = "paladin;pala;pally"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "<:priest:945492995602526238>",
                            Name = "Priest",
                            SearchTerms = "priest"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "<:rogue:945492995480883210>",
                            Name = "Rogue",
                            SearchTerms = "rogue;rouge"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "<:shaman:945492995459940402>",
                            Name = "Shaman",
                            SearchTerms = "shaman;shammy;sham"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "<:warlock:945492995648671754>",
                            Name = "Warlock",
                            SearchTerms = "warlock;lock"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "<:warrior:945492995602538546>",
                            Name = "Warrior",
                            SearchTerms = "warrior;warr"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "<:deathknight:945492994964979722>",
                            Name = "Death Knight",
                            SearchTerms = "death knight;deathknight;dk"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "<:monk:945492996554629170>",
                            Name = "Monk",
                            SearchTerms = "monk"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "<:demonhunter:945492995149545552>",
                            Name = "Demon Hunter",
                            SearchTerms = "demon hunter;demonhunter;dh"
                        },
                        new
                        {
                            Id = 13,
                            Icon = "<:evoker:1179290186530697296>",
                            Name = "Evoker",
                            SearchTerms = "evoker"
                        });
                });

            modelBuilder.Entity("RaidBot.Data.PlayerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "<:tank:945067186421116958>",
                            Name = "Tanks",
                            SearchTerms = "tank;t"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "<:healer:945067186542772244>",
                            Name = "Healers",
                            SearchTerms = "healer;heals;heal;h"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "<:rdps:945067186203033691>",
                            Name = "Ranged",
                            SearchTerms = "ranged;caster;rdps;r"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "<:mdps:945067186421104670>",
                            Name = "Melee",
                            SearchTerms = "melee;mdps;m"
                        });
                });

            modelBuilder.Entity("RaidBot.Data.Raid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("RaidBot.Data.RaidMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaidId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RaidId");

                    b.HasIndex("RoleId");

                    b.ToTable("RaidMembers");
                });

            modelBuilder.Entity("RaidBot.Data.ExpansionClass", b =>
                {
                    b.HasOne("RaidBot.Data.PlayerClass", "Class")
                        .WithMany("ExpansionClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.Data.Expansion", "Expansion")
                        .WithMany("ExpansionClasses")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("RaidBot.Data.GuildExpansionConfiguration", b =>
                {
                    b.HasOne("RaidBot.Data.Expansion", "Expansion")
                        .WithMany("GuildExpansionConfigurations")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("RaidBot.Data.Raid", b =>
                {
                    b.HasOne("RaidBot.Data.GuildExpansionConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("RaidBot.Data.RaidMember", b =>
                {
                    b.HasOne("RaidBot.Data.PlayerClass", "Class")
                        .WithMany("Members")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.Data.Raid", "Raid")
                        .WithMany("Members")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.Data.PlayerRole", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Raid");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaidBot.Data.Expansion", b =>
                {
                    b.Navigation("ExpansionClasses");

                    b.Navigation("GuildExpansionConfigurations");
                });

            modelBuilder.Entity("RaidBot.Data.PlayerClass", b =>
                {
                    b.Navigation("ExpansionClasses");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("RaidBot.Data.PlayerRole", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RaidBot.Data.Raid", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
